# Generated by Django 2.0.5 on 2018-10-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fk_product', models.IntegerField(default='0')),
                ('fk_buyer', models.IntegerField(default='0')),
                ('buyer_message', models.CharField(max_length=140)),
                ('quantity', models.IntegerField(default='0')),
                ('total_price', models.FloatField(default='0.0')),
                ('closed', models.BooleanField(default=False)),
                ('product_name', models.TextField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
