# Generated by Django 2.0.8 on 2018-10-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='closed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(default='0'),
        ),
    ]
